name: Create rolling release

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
      - '.github/ISSUE_TEMPLATE/*'
  push:
    branches:
      - custom
      - mml
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
      - '.github/ISSUE_TEMPLATE/*'
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          dep/msvc/deps-arm64
          dep/msvc/deps-x64
        key: deps ${{ hashFiles('scripts/build-dependencies-windows-arm64.bat', 'scripts/build-dependencies-windows-x64.bat') }}

    - name: Build X64 Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      env:
        DEBUG: 0
      run: scripts/build-dependencies-windows-x64.bat

    - name: Build ARM64 Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      env:
        DEBUG: 0
      run: scripts/build-dependencies-windows-arm64.bat

    - name: Tag as preview build
      if: github.ref == 'refs/heads/master'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-x64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "preview"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "preview" >> src/scmversion/tag.h

    - name: Tag as custom build
      if: github.ref == 'refs/heads/custom'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-x64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "custom"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "custom" >> src/scmversion/tag.h

    - name: Tag as mml build
      if: github.ref == 'refs/heads/mml'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-x64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "mml"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "mml" >> src/scmversion/tag.h

    - name: Update RC version fields
      shell: cmd
      run: |
        cd src\scmversion
        git describe --dirty --always
        call update_rc_version.bat
        cd ..\..
        git update-index --assume-unchanged src/duckstation-qt/duckstation-qt.rc
        git update-index --assume-unchanged src/duckstation-nogui/duckstation-nogui.rc
        cat src/duckstation-qt/duckstation-qt.rc | grep VERSION
        cat src/duckstation-qt/duckstation-qt.rc | grep Version


    - name: Compile x64 release build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        msbuild duckstation.sln -t:Build -p:Platform=x64;Configuration=ReleaseLTCG

    - name: Create x64 symbols archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation-windows-x64-release-symbols.zip ./bin/x64/*.pdb

    - name: Upload x64 release symbols artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows"
        path: "duckstation-windows-x64-release-symbols.zip"

    - name: Remove extra bloat before archiving
      shell: cmd
      run: |
        del /Q bin\x64\*.pdb bin\x64\*.exp bin\x64\*.lib bin\x64\*.iobj bin\x64\*.ipdb bin\x64\common-tests*
        rename bin\x64\updater-x64-ReleaseLTCG.exe updater.exe

    - name: Create x64 release archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation-windows-x64-release.zip ./bin/x64/*

    - name: Upload x64 release artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows"
        path: "duckstation-windows-x64-release.zip"


  windows-arm64-build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
        submodules: true

    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          dep/msvc/deps-arm64
          dep/msvc/deps-x64
        key: deps ${{ hashFiles('scripts/build-dependencies-windows-arm64.bat', 'scripts/build-dependencies-windows-x64.bat') }}

    - name: Build X64 Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      env:
        DEBUG: 0
      run: scripts/build-dependencies-windows-x64.bat

    - name: Build ARM64 Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      env:
        DEBUG: 0
      run: scripts/build-dependencies-windows-arm64.bat

    - name: Tag as preview build
      if: github.ref == 'refs/heads/master'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-arm64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "preview"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "preview" >> src/scmversion/tag.h

    - name: Tag as custom build
      if: github.ref == 'refs/heads/custom'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-arm64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "custom"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "custom" >> src/scmversion/tag.h

    - name: Tag as mml build
      if: github.ref == 'refs/heads/mml'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-arm64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "mml"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "mml" >> src/scmversion/tag.h

    - name: Update RC version fields
      shell: cmd
      run: |
        cd src\scmversion
        call update_rc_version.bat
        cd ..\..
        git update-index --assume-unchanged src/duckstation-qt/duckstation-qt.rc
        git update-index --assume-unchanged src/duckstation-nogui/duckstation-nogui.rc

    - name: Compile arm64 release build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64_arm64
        msbuild duckstation.sln -t:Build -p:Platform=ARM64;Configuration=ReleaseLTCG

    - name: Create arm64 symbols archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation-windows-arm64-release-symbols.zip ./bin/ARM64/*.pdb

    - name: Upload arm64 release symbols artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows-arm64"
        path: "duckstation-windows-arm64-release-symbols.zip"

    - name: Remove extra bloat before archiving
      shell: cmd
      run: |
        del /Q bin\ARM64\*.pdb bin\ARM64\*.exp bin\ARM64\*.lib bin\ARM64\*.iobj bin\ARM64\*.ipdb bin\ARM64\common-tests*
        rename bin\ARM64\updater-ARM64-ReleaseLTCG.exe updater.exe

    - name: Create arm64 release archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation-windows-arm64-release.zip ./bin/ARM64/*

    - name: Upload arm64 release artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows-arm64"
        path: "duckstation-windows-arm64-release.zip"


  linux-build:
    runs-on: ubuntu-22.04
    steps:
    # Work around https://github.com/actions/runner-images/issues/8659
    - name: Remove GCC 13 from runner image
      shell: bash
      run: |
        sudo rm -f /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-jammy.list
        sudo apt-get update
        sudo apt-get install -y --allow-downgrades libc6=2.35-0ubuntu3.4 libc6-dev=2.35-0ubuntu3.4 libstdc++6=12.3.0-1ubuntu1~22.04 libgcc-s1=12.3.0-1ubuntu1~22.04

    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Install packages
      shell: bash
      run: |
        # Workaround for https://github.com/actions/runner-images/issues/675
        scripts/retry.sh wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo scripts/retry.sh apt-add-repository -n 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main'

        sudo scripts/retry.sh apt-get update &&
        sudo scripts/retry.sh apt-get -y install \
          cmake ninja-build ccache libegl1-mesa-dev libevdev-dev libwayland-dev libwayland-egl-backend-dev libxrandr-dev libdbus-1-dev \
          extra-cmake-modules libcurl4-openssl-dev libssl-dev libasound2-dev libpulse-dev libx11-xcb-dev build-essential git libclang-dev \
          libclang-11-dev libclang-12-dev patchelf libglib2.0-dev libfontconfig1-dev libharfbuzz-dev libjpeg-dev libpng-dev libfreetype-dev \
          libinput-dev libxcb-*-dev libxkbcommon-dev libxkbcommon-x11-dev libxrender-dev libwayland-dev libgl1-mesa-dev libegl-dev \
          libegl1-mesa-dev libgl1-mesa-dev libssl-dev libx11-dev libx11-xcb-dev libfuse2 llvm-16 lld-16 clang-16

    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ~/deps
        key: deps ${{ hashFiles('scripts/build-dependencies.sh') }}

    - name: Build Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: scripts/build-dependencies.sh

    - name: Tag as preview build
      if: github.ref == 'refs/heads/master'
      run: |
        echo '#pragma once' > src/scmversion/tag.h
        echo '#define SCM_RELEASE_ASSET "DuckStation-x64.AppImage"' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAGS {"latest", "preview"}' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAG "preview"' >> src/scmversion/tag.h

    - name: Tag as custom build
      if: github.ref == 'refs/heads/custom'
      run: |
        echo '#pragma once' > src/scmversion/tag.h
        echo '#define SCM_RELEASE_ASSET "DuckStation-x64.AppImage"' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAGS {"latest", "custom"}' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAG "custom"' >> src/scmversion/tag.h

    - name: Tag as mml build
      if: github.ref == 'refs/heads/mml'
      run: |
        echo '#pragma once' > src/scmversion/tag.h
        echo '#define SCM_RELEASE_ASSET "DuckStation-x64.AppImage"' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAGS {"latest", "mml"}' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAG "mml"' >> src/scmversion/tag.h


    - name: Compile build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DCMAKE_PREFIX_PATH=$HOME/deps -DCMAKE_TOOLCHAIN_FILE=../scripts/clang-toolchain.cmake ..
        cmake --build . --parallel
        cd ..
        scripts/appimage/make-appimage.sh $(realpath .) $(realpath ./build) $HOME/deps DuckStation-x64

    - name: Upload Qt AppImage
      uses: actions/upload-artifact@v1
      with:
        name: "linux-x64-appimage-qt"
        path: "DuckStation-x64.AppImage"


  linux-flatpak-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install packages
      shell: bash
      run: scripts/flatpak/install-packages.sh

    - name: Generate AppStream XML
      run: |
        scripts/generate-metainfo.sh scripts/flatpak
        cat scripts/flatpak/org.duckstation.DuckStation.metainfo.xml
        flatpak run org.freedesktop.appstream-glib validate scripts/flatpak/org.duckstation.DuckStation.metainfo.xml

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: duckstation-x64.flatpak
        manifest-path: scripts/flatpak/org.duckstation.DuckStation.json
        arch: x86_64
        build-bundle: true
        verbose: true
        #mirror-screenshots-url: https://dl.flathub.org/repo/screenshots
        #branch: ${{ inputs.branch }}
        branch: master
        cache: true
        restore-cache: true
        cache-key: flatpak-x64-${{ hashFiles('.scripts/flatpak/**/*.json') }}

#    - name: Commit screenshots to OSTree
#      run: |
#        ostree commit --repo=repo --canonical-permissions --branch=screenshots/x86_64 flatpak_app/screenshots

    - name: Upload Flatpak
      uses: actions/upload-artifact@v1
      with:
        name: "linux-flatpak"
        path: "duckstation-x64.flatpak"


  macos-build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    # Python 3.12 removed distutils, used by MoltenVK -> glslang.
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install packages
      shell: bash
      run: |
        brew install curl ninja

    - name: Cache Dependencies
      id: cache-deps-mac
      uses: actions/cache@v3
      with:
        path: ~/deps
        key: deps-mac ${{ hashFiles('scripts/build-dependencies-mac.sh') }}

    - name: Build Dependencies
      if: steps.cache-deps-mac.outputs.cache-hit != 'true'
      run: scripts/build-dependencies-mac.sh

    - name: Tag as preview build
      if: github.ref == 'refs/heads/master'
      run: |
        echo '#pragma once' > src/scmversion/tag.h
        echo '#define SCM_RELEASE_ASSET "duckstation-mac-release.zip"' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAGS {"latest", "preview"}' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAG "preview"' >> src/scmversion/tag.h

    - name: Tag as custom build
      if: github.ref == 'refs/heads/custom'
      run: |
        echo '#pragma once' > src/scmversion/tag.h
        echo '#define SCM_RELEASE_ASSET "duckstation-mac-release.zip"' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAGS {"latest", "custom"}' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAG "custom"' >> src/scmversion/tag.h

    - name: Tag as mml build
      if: github.ref == 'refs/heads/mml'
      run: |
        echo '#pragma once' > src/scmversion/tag.h
        echo '#define SCM_RELEASE_ASSET "duckstation-mac-release.zip"' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAGS {"latest", "mml"}' >> src/scmversion/tag.h
        echo '#define SCM_RELEASE_TAG "mml"' >> src/scmversion/tag.h

    - name: Compile and zip .app
      shell: bash
      run: |
        mkdir build
        cd build
        export MACOSX_DEPLOYMENT_TARGET=11.0
        cmake -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENGL=OFF -DCMAKE_PREFIX_PATH="$HOME/deps" -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -G Ninja ..
        cmake --build . --parallel
        mv bin/DuckStation.app .
        codesign -s - --deep -f -v DuckStation.app
        zip -r duckstation-mac-release.zip DuckStation.app/

    - name: Upload macOS .app
      uses: actions/upload-artifact@v1
      with:
        name: "macos"
        path: "build/duckstation-mac-release.zip"


  create-release:
    needs: [windows-build, windows-arm64-build, linux-build, linux-flatpak-build, macos-build]
    runs-on: "ubuntu-20.04"
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/custom' || github.ref == 'refs/heads/mml'
    steps:
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v1
        with:
          name: "windows"

      - name: Download Windows ARM64 Artifact
        uses: actions/download-artifact@v1
        with:
          name: "windows-arm64"

      - name: Download Qt AppImage Artifact
        uses: actions/download-artifact@v1
        with:
          name: "linux-x64-appimage-qt"

      - name: Download Flatpak Artifact
        uses: actions/download-artifact@v1
        with:
          name: "linux-flatpak"

      - name: Download MacOS Artifact
        uses: actions/download-artifact@v1
        with:
          name: "macos"

      - name: Create preview release
        if: github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "preview"
          prerelease: true
          title: "Latest Preview Build"
          files: |
            windows/duckstation-windows-x64-release.zip
            windows/duckstation-windows-x64-release-symbols.zip
            windows-arm64/duckstation-windows-arm64-release.zip
            windows-arm64/duckstation-windows-arm64-release-symbols.zip
            linux-x64-appimage-qt/DuckStation-x64.AppImage
            linux-flatpak/duckstation-x64.flatpak
            macos/duckstation-mac-release.zip

      - name: Create custom release
        if: github.ref == 'refs/heads/custom'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "custom"
          prerelease: false
          title: "Latest Custom Build"
          files: |
            windows/duckstation-windows-x64-release.zip
            windows/duckstation-windows-x64-release-symbols.zip
            windows-arm64/duckstation-windows-arm64-release.zip
            windows-arm64/duckstation-windows-arm64-release-symbols.zip
            linux-x64-appimage-qt/DuckStation-x64.AppImage
            linux-flatpak/duckstation-x64.flatpak
            macos/duckstation-mac-release.zip

      - name: Create mml release
        if: github.ref == 'refs/heads/mml'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "mml"
          prerelease: false
          title: "Latest MML Build"
          files: |
            windows/duckstation-windows-x64-release.zip
            windows/duckstation-windows-x64-release-symbols.zip
            windows-arm64/duckstation-windows-arm64-release.zip
            windows-arm64/duckstation-windows-arm64-release-symbols.zip
            linux-x64-appimage-qt/DuckStation-x64.AppImage
            linux-flatpak/duckstation-x64.flatpak
            macos/duckstation-mac-release.zip

